name: Build and save my Docker image to a regitry

on:
  push:
    paths:
      - 'src/backend/**'
      - '.github/workflows/ci-backend.yml'
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "acrinfobi22210.azurecr.io" # Nom du registry
  IMAGE_NAME: "be-jbdr" # Nom de votre image

jobs:
  build-and-deploy:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: docker-build-action
        uses: serversideup/github-action-docker-build@v6
        with:
          context: ./src/backend
          dockerfile: ./src/backend/Dockerfile
          tags: ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          registry: ${{ env.REG_NAME}}
          registry-username: ${{ secrets.REGISTRY_USER }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
